import type { IconProps } from '@phosphor-icons/react';
import {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  Bell,
  Briefcase,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  CalendarBlank,
  Check,
  CheckCircle,
  Circle,
  Clock,
  Coffee,
  Compass,
  Envelope,
  EnvelopeOpen,
  Eye,
  EyeSlash,
  Factory,
  Flame,
  Flask,
  Gear,
  Globe,
  GridFour,
  Heart,
  House,
  Leaf,
  Lightning,
  Lock,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MapPin,
  MapTrifold,
  Moon,
  NotePencil,
  Palette,
  PaperPlaneTilt,
  PawPrint,
  PencilSimple,
  Phone,
  Rocket,
  SealCheck,
  ShareNetwork,
  ShoppingCart,
  SignIn,
  SignOut,
  SlidersHorizontal,
  SortAscending,
  Sparkle,
  Star,
  Storefront,
  Sun,
  SunHorizon,
  TrendUp,
  User,
  UsersThree,
  Warning,
  WarningCircle,
  WifiHigh,
  Wrench,
  X,
  XCircle,
  Drop,
  ChatCircleText,
} from '@phosphor-icons/react';

export type PhosphorIconComponent = React.ComponentType<IconProps>;

export const MATERIAL_ICON_MAP: Record<string, PhosphorIconComponent> = {
  add_business: Storefront,
  apps: GridFour,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkle,
  call: Phone,
  calendar_today: CalendarBlank,
  store: Storefront,
  cancel: XCircle,
  check: Check,
  check_circle: CheckCircle,
  chevron_left: CaretLeft,
  chevron_right: CaretRight,
  circle: Circle,
  close: X,
  coffee: Coffee,
  coffee_maker: Coffee,
  deck: SunHorizon,
  eco: Leaf,
  edit: PencilSimple,
  edit_note: NotePencil,
  edit_square: NotePencil,
  energy: Lightning,
  error: WarningCircle,
  expand_more: CaretDown,
  explore: Compass,
  favorite: Heart,
  grid_view: GridFour,
  groups: UsersThree,
  language: Globe,
  light_mode: Sun,
  local_cafe: Coffee,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  login: SignIn,
  logout: SignOut,
  mail: Envelope,
  mark_email_read: EnvelopeOpen,
  notifications: Bell,
  palette: Palette,
  person: User,
  pets: PawPrint,
  photo_camera: Camera,
  pin_drop: MapPin,
  precision_manufacturing: Factory,
  public: Globe,
  rate_review: ChatCircleText,
  refresh: ArrowClockwise,
  rocket_launch: Rocket,
  schedule: Clock,
  science: Flask,
  search: MagnifyingGlass,
  search_off: MagnifyingGlassMinus,
  send: PaperPlaneTilt,
  settings: Gear,
  share: ShareNetwork,
  shopping_cart_checkout: ShoppingCart,
  star: Star,
  swap_vert: SortAscending,
  tool: Wrench,
  trending_up: TrendUp,
  tune: SlidersHorizontal,
  verified: SealCheck,
  visibility: Eye,
  visibility_off: EyeSlash,
  warning: Warning,
  water_drop: Drop,
  wifi: WifiHigh,
  dark_mode: Moon,
  briefcase: Briefcase,
  map: MapTrifold,
  home: House,
  info: WarningCircle,
  checkin: MapPin,
};

export type MaterialIconName = keyof typeof MATERIAL_ICON_MAP;

export function isMaterialIconName(name: string): name is MaterialIconName {
  return name in MATERIAL_ICON_MAP;
}
