---
deployment:
  tasks:
    - export DEPLOYPATH=/home/coffeepeek/public_html/
    
    # Navigate to project directory
    - cd coffee-peek || cd .
    
    # Install dependencies
    - npm install
    
    # Build the project
    - npm run build
    
    # Copy built files to deployment directory
    - /bin/cp -R dist/* $DEPLOYPATH
    
    # Optional: Copy .htaccess if needed for SPA routing
    - echo "Creating .htaccess for SPA routing..."
    - echo "RewriteEngine On" > $DEPLOYPATH/.htaccess
    - echo "RewriteBase /" >> $DEPLOYPATH/.htaccess
    - echo "RewriteRule ^index\.html$ - [L]" >> $DEPLOYPATH/.htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-f" >> $DEPLOYPATH/.htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-d" >> $DEPLOYPATH/.htaccess
    - echo "RewriteRule . /index.html [L]" >> $DEPLOYPATH/.htaccess

